openapi: '3.0.2'
info:
  title: Note app RESTful API
  version: '1.0'
  contact:
    email: nurahmanmulya@gmail.com
    name: Ikhlash Mulyanurahman
servers:
  - url: http://localhost:3000/api
tags:
  - name: note
paths:
  /notes:
    post:
      tags:
        - "note"
      security:
        - authApiKey: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/noteCreateAndUpdate"
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status: 
                    type: string
                  message:
                    type: string
                  data: 
                    type: object
                    properties:
                      id: 
                        type: string
        '500':
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
        '401':
          $ref: "#/components/responses/unauthorized"
    get:
      tags:
        - "note"
      security:
        - authApiKey: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/note"
        '401':
          $ref: "#/components/responses/unauthorized"
  /notes/{noteId}:
    get:
      tags:
        - "note"
      security:
        - authApiKey: []
      parameters:
        - required: true
          $ref: "#/components/parameters/noteId"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/note"
        '404':
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
        '401':
          $ref: "#/components/responses/unauthorized"
    put:
      tags:
        - "note"
      security:
        - authApiKey: []
      parameters:
        - required: true
          $ref: "#/components/parameters/noteId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/noteCreateAndUpdate"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/noteCreateAndUpdate"
        '404':
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
        '401':
          $ref: "#/components/responses/unauthorized"
    delete:
      tags:
        - "note"
      security:
        - authApiKey: []
      parameters:
        - required: true
          $ref: "#/components/parameters/noteId"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
        '404':
          description: NOT FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  status:
                    type: string
                  message:
                    type: string
        '401':
          $ref: "#/components/responses/unauthorized"
components:
  securitySchemes:
    authApiKey:
      type: apiKey
      name: X-API-Key
      in: header
  parameters:
    noteId:
      name: noteId
      in: path
      required: true
      schema:
        type: string
  schemas:
    note: 
      type: object
      properties:
        id: 
          type: string
        title:
          type: string
        created_at:
          type: string
        update_at:
          type: string
        tags:
          type: array
          items:
            type: string
        items:
          type: string
        body: 
          type: string
    noteCreateAndUpdate:
      type: object
      properties:
        title:
          type: string
        tags:
          type: array
          items:
            type: string
        body: 
          type: string
      example:
        title: "Judul catatan"
        tags: 
          - "tags 1"
          - "tags 2"
        body: "Konten catatan"
  responses:
    unauthorized:
      description: UNAUTHORIZED 
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              status:
                type: string
          example:
            code: 401
            status: "UNAUTHORIZED"